apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bluebubbles-chatgpt-agent
resources:
- be-components.yaml
- keycloak-bbagent/keycloak-bbagent.yaml
images:
- name: ghcr.io/omega-bred/bluebubbles-chatgpt-agent
  newName: ghcr.io/omega-bred/bluebubbles-chatgpt-agent
  newTag: 1379468927d0f1d17d496c98a052337512d1aec7-665
- name: ghcr.io/omega-bred/bluebubbles-chatgpt-agent-lxmf-bridge
  newName: ghcr.io/omega-bred/bluebubbles-chatgpt-agent-lxmf-bridge
  newTag: 1379468927d0f1d17d496c98a052337512d1aec7-665
