apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bluebubbles-chatgpt-agent
resources:
- be-components.yaml
images:
- name: ghcr.io/omega-bred/bluebubbles-chatgpt-agent
  newName: ghcr.io/omega-bred/bluebubbles-chatgpt-agent
  newTag: 65712e76bba8618a5816735c55839539f62a4d15-450
- name: ghcr.io/omega-bred/bluebubbles-chatgpt-agent-lxmf-bridge
  newName: ghcr.io/omega-bred/bluebubbles-chatgpt-agent-lxmf-bridge
  newTag: 65712e76bba8618a5816735c55839539f62a4d15-450
