apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bluebubbles-chatgpt-agent
resources:
- be-components.yaml
images:
- name: ghcr.io/omega-bred/bluebubbles-chatgpt-agent
  newName: ghcr.io/omega-bred/bluebubbles-chatgpt-agent
  newTag: b6eb97f28411ba07b4c1a269c94a868c90a06a5c-318
- name: ghcr.io/omega-bred/bluebubbles-chatgpt-agent-lxmf-bridge
  newName: ghcr.io/omega-bred/bluebubbles-chatgpt-agent-lxmf-bridge
  newTag: b6eb97f28411ba07b4c1a269c94a868c90a06a5c-318
